
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Hero from "./components/hero/Hero";
import Footer from "./components/footer/Footer";
import Modal from "./components/modals/Modal";
import { getUserId } from "./lib/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  const userId = await getUserId();


  const content = ( <p>content</p>)

  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar initialUserId={userId} />
        <div className="pt-[65px] flex-grow">
        {children}
        </div>
        <Footer />
      </body>
        
    </html>
  );
}
